<?php
/**
 * Seller Product list template
 *
 * @see Webkul_Marketplace_Block_Collection
 */
?>
<?php 
$partner=$this->getProfileDetail();
if($partner->getprofileurl()!=''){
    if(Mage::getStoreConfig('marketplace/seller_profile/activecolorpicker')){?> 
        <style>
        .main{background-image:none;background-color:<?php echo $partner->getBackgroundth();?>;}
        </style>
    <?php
    }
    $_productCollection=$this->getCollection();
    $_helper = $this->helper('catalog/output');
    $helper=Mage::helper('marketplace');
    $partner=$this->getProfileDetail();
    $productname=$this->getRequest()->getParam('name');
    $bannerpic=$partner->getbannerpic()!=''?$partner->getbannerpic():"banner-image.png";
    $bannerpic=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'avatar/'.$bannerpic;
    ?>
    <?php
    $theme = $this->helper('ultimo');
    $helpLabels = $this->helper('ultimo/labels');
    $helpTemplate = $this->helper('ultimo/template');
    $helpImg = $this->helper('infortis/image');
    $_collectionSize = $_productCollection->count();

    //Default image size
    $imgWidth = 295;
    $imgHeight = 295;

    //Aspect ratio settings
    if ($theme->getCfg('category/aspect_ratio'))
        $imgHeight = 0; //Height will be computed automatically (based on width) to keep the aspect ratio

    //Hide toolbar
    $hideToolbar = false;
    if ($this->getHideToolbar())
    {
        $hideToolbar = true;
    }
    ?>
    <div class="collection-banner"><img src="<?php echo $bannerpic; ?>" alt="no image"></img></div>
    <div class="wk_mp_design" style="padding-top: 10px;">
        <div class="block block-account">   
            <div class="block-title">   
                <strong><span><h4><?php echo $helper->__("SELLER'S COLLECTION") ?></h4></span></strong>
            </div>
        </div>
        <div class="fieldset wk_mp_fieldset" <?php if($_productCollection->count()){ echo 'style="padding: 0;"';}?>>
            <?php if(!$_productCollection->count()): ?>
            <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
            <?php else: ?>

                <div class="category-products">
                    <?php if (!$hideToolbar): ?>
                        <?php echo $this->getToolbarHtml() ?>
                    <?php endif; ?>
                    <?php if($this->getMode()!='grid'): //List mode ?>

                    <?php
                        //Get list configuration array
                        $lc = $theme->getCfgGroup('category_list');
                        
                        //List classes
                        $listClasses = '';
                        if ($lc['hover_effect'])
                            $listClasses = ' hover-effect';


                    ?>

                    <?php $_iterator = 0; ?>
                    <ul class="products-list<?php if($listClasses) echo $listClasses; ?>" id="products-list">
                    <?php foreach ($_productCollection as $_product): ?>
                        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">

                            <?php //Product Image ?>
                            <div class="product-image-wrapper grid12-4 mobile-grid-half">

                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image" style="max-width:<?php echo $imgWidth; ?>px;">
                                    <img src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                    
                                    <?php if ($theme->getCfg('category/alt_image')): ?>
                                        <?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>
                                    <?php endif; ?>
                                    
                                    <?php echo $helpLabels->getLabels($_product); //Product labels ?>
                                </a>

                            </div> <!-- end: product-image-wrapper -->

                            <?php //Product description ?>
                            <div class="product-shop grid12-5 mobile-grid-half">
                                <div class="product-shop-inner">
                                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                                    <?php if($_product->getRatingSummary()): ?>
                                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                    <?php endif; ?>
                                    
                                    <div class="desc std">
                                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                    </div>
                                </div>
                            </div>
                                
                            <div class="right-column grid12-3 mobile-grid-half">
                                <?php echo $this->getPriceHtml($_product, true) ?>
                                <?php if($_product->isSaleable()): ?>
                                    <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                                
                                <?php
                                if ($lc['addtolinks_simple'])
                                    echo $helpTemplate->getCategoryAddtoLinks($_product, $this->getAddToCompareUrl($_product), 'addto-gaps-right');
                                else
                                    echo $helpTemplate->getCategoryAddtoLinksComplex($_product, $this->getAddToCompareUrl($_product), 'addto-gaps-right');
                                ?>
                            </div>

                        </li>
                    <?php endforeach; ?>
                    </ul>
                    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

                    <?php else: //Grid mode ?>

                    <?php
                        //Get grid configuration array
                        $gc = $theme->getCfgGroup('category_grid');
                        
                        //Get number of columns (from parameter or from theme config)
                        $columnCount = 3;
                        if ($this->getGridColumnCount())
                        {
                            $columnCount = $this->getGridColumnCount();
                        }
                        else
                        {
                            $columnCount = $gc['column_count'];
                        }

                        //Grid classes
                        $gridClasses = '';
                        if ($gc['display_name'] == 2 && $gc['display_name_single_line'] == true)
                            $gridClasses .= ' single-line-name';
                        if ($gc['centered'])
                            $gridClasses .= ' centered';
                        if ($gc['hover_effect'])
                            $gridClasses .= ' hover-effect';
                        if ($gc['equal_height'])
                            $gridClasses .= ' equal-height';

                        //Size of grid elements
                        if ($gc['elements_size'])
                        {
                            $gridClasses .= ' size-' . $gc['elements_size'];
                        }
                        else
                        {
                            //Calculate size based on number of columns
                            if ($columnCount >= 6)
                            {
                                $gridClasses .= ' size-xs';
                            }
                            elseif ($columnCount >= 4)
                            {
                                $gridClasses .= ' size-s';
                            }
                        }

                        //Container "actions" at the bottom of the grid item stores button and add-to links
                        //If at least one of those elements was set as "Display on hover" but no element was set as "Display":
                        //apply appropriate classes to the container.
                        $actionsClasses = '';
                        if ($gc['display_addtocart'] == 1 || ($gc['display_addtolinks'] == 1 && !$gc['addtolinks_simple']))
                        {
                            $actionsClasses = ' display-onhover';
                        }
                        if ($gc['display_addtocart'] == 2 || ($gc['display_addtolinks'] == 2 && !$gc['addtolinks_simple']))
                        {
                            $actionsClasses = '';
                        }
                    ?>
                    
                    <ul class="products-grid category-products-grid itemgrid itemgrid-adaptive itemgrid-<?php echo $columnCount; ?>col<?php if($gridClasses) echo $gridClasses; ?>">
                        <?php foreach ($_productCollection as $_product): ?>
                            <li class="item">
                            
                                <div class="product-image-wrapper" style="max-width:<?php echo $imgWidth; ?>px;">
                                
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" class="product-image">
                                        <img src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />

                                        <?php if ($theme->getCfg('category/alt_image')): ?>
                                            <?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>   
                                        <?php endif; ?>

                                        <?php echo $helpLabels->getLabels($_product); //Product labels ?>
                                    </a>
                                
                                    <?php //Add-to links
                                        if ($gc['display_addtolinks'] != 0 && $gc['addtolinks_simple'])
                                        {
                                            if ($gc['display_addtolinks'] == 1) //Display on hover
                                                echo $helpTemplate->getCategoryAddtoLinksComplex_2($_product, $this->getAddToCompareUrl($_product), 'addto-links-icons addto-onimage display-onhover');
                                            else //Always display
                                                echo $helpTemplate->getCategoryAddtoLinksComplex_2($_product, $this->getAddToCompareUrl($_product), 'addto-links-icons addto-onimage');
                                        }
                                    ?>
                                
                                </div> <!-- end: product-image-wrapper -->
                                
                                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                                
                                <?php if($_product->getRatingSummary()): ?>
                                    <?php if ($gc['display_rating'] == 1): //Display on hover ?>
                                        <div class="display-onhover"><?php echo $this->getReviewsSummaryHtml($_product, 'short') ?></div>
                                    <?php elseif ($gc['display_rating'] == 2): //Always display ?>
                                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                                
                                <?php if ($gc['display_price'] == 1) echo '<div class="display-onhover">'; ?>
                                    <?php echo $this->getPriceHtml($_product, true); ?>
                                <?php if ($gc['display_price'] == 1) echo '</div>'; ?>

                                <?php
                                    //If at least one element was set as "Display on hover" but no element was set as "Display":
                                    //aggregate classes from those elements and apply them to the "actions" container.
                                    $actionsClasses = '';
                                    if ($gc['display_addtocart'] == 1 || ($gc['display_addtolinks'] == 1 && !$gc['addtolinks_simple']))
                                    {
                                        $actionsClasses = ' display-onhover';
                                    }
                                    if ($gc['display_addtocart'] == 2 || ($gc['display_addtolinks'] == 2 && !$gc['addtolinks_simple']))
                                    {
                                        $actionsClasses = '';
                                    }
                                ?>
                                
                                <div class="actions clearer<?php echo $actionsClasses; ?>">
                                    <?php //Cart button ?>
                                    <?php if ($gc['display_addtocart'] != 0): ?>
                                        <?php if ($_product->isSaleable()): ?>
                                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                        <?php else: ?>
                                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    
                                    <?php //Add-to links
                                        if ($gc['display_addtolinks'] != 0 && !$gc['addtolinks_simple'])
                                        {
                                            echo $helpTemplate->getCategoryAddtoLinks($_product, $this->getAddToCompareUrl($_product), 'addto-gaps-right addto-texticons');
                                        }
                                    ?>
                                </div> <!-- end: actions -->
                            </li>
                        <?php endforeach; ?>    
                    </ul>
                    <?php endif; //end: if grid mode ?>

                    <?php if (!$hideToolbar): ?>
                        <div class="toolbar-bottom">
                            <?php echo $this->getToolbarHtml() ?>
                        </div>
                    <?php endif; ?>
                </div>

                <?php if ($_collectionSize && $tmpHtml = $this->getChildHtml('block_category_below_collection')): ?>
                    <div class="block_category_below_collection std"><?php echo $tmpHtml; ?></div>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>
    <script type="text/javascript">
        if (typeof jQuery == 'undefined'){
            document.write(unescape("%3Cscript src='//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
        }
    </script>
    <script>    
    jQuery.noConflict();
    (function($wk_jq){
        $wk_jq('.toolbar select option').each(function(){
            $url=$wk_jq(this).attr('value').replace('collection/','collection/'+'<?php echo $partner->getprofileurl();?>/');
            $wk_jq(this).attr('value',$url);
        });
        $wk_jq('.toolbar a').each(function(){
            $wk_jq(this).attr('href',$wk_jq(this).attr('href').replace('collection/','collection/'+'<?php echo $partner->getprofileurl();?>/'));
        });
    })(jQuery);

    </script>
<?php } ?>