<div class="wk_maindata">
<?php  $data=$this->getMpsellerfeepay(); 
        $collection =Mage::getModel('mppartnergroup/assinegroup')->getCollection();
        $collection->addFieldToFilter('partner_id', array('eq' => $data['customer_id']));
        $collection->addFieldToFilter('expiry_date', array('gt' => date('Y-m-d')));
        if(count($collection)>0){
			foreach ($collection as $transaction){
				$isPartner= Mage::getModel('marketplace/userprofile')->isPartner();
				if($isPartner==1){
				?>
                <div class="page-title">
					<h1><?php echo Mage::helper('marketplace')->__('Payment Detail of Seller') ?></h1>
				</div>
				<div class="fieldset">
					<h4 class="legend"><?php echo Mage::helper('marketplace')->__('Payment Detail') ?></h4>
					<ul class="form-list">
						<li>
							<div class="input-box">
								<label><?php echo $this->__('Transaction ID : '); ?></label>
								<?php echo $transaction->getTransactionId();?>
							</div>
						</li>
						<li>
							<div class="input-box">
								<label><?php echo $this->__('Transaction Email : '); ?></label>
								<?php echo $transaction->getTransactionEmail();?>
							</div>
						</li>
						<li>
							<div class="input-box">
								<label><?php echo $this->__('IPN Transaction ID : '); ?></label>
								<?php echo $transaction->getIpnTransactionId();?>
							</div>
						</li>
						<li>
							<div class="input-box">
								<label><?php echo $this->__('Seller Group : '); ?></label>
								<?php echo $transaction->getType();?>
							</div>
						</li>
						<li>
							<div class="input-box">
								<label><?php echo $this->__('Transaction Date : '); ?></label>
								<?php echo $transaction->getTransactionDate();?>
							</div>
						</li>
						<li>
							<div class="input-box">
								<label><?php echo $this->__('Expiry Date : '); ?></label>
								<?php echo $transaction->getExpiryDate();?>
							</div>
						</li>
						<li>
							<div class="input-box">
								<label><?php echo $this->__('Transaction Status : '); ?></label>
								<?php echo $transaction->getTransactionStatus();?>
							</div>
						</li>
					</ul>
                </div>
			<?php }else{?>
				<div class="wk_adminmsg">Your Are locked By Admin</div>
			<?php }
			}
        }
        else{ 
			$urlfix="";
			if($data['merchant']==NULL ){ ?>
				<div class="wk_adminmsg">Payment is not allowed due to some technical issues...</div>
        <?php } else{ if($data['sandbox']==1){ $urlfix="sandbox.";}  ?>
		<div class="page-title">
			<h1><?php echo Mage::helper('marketplace')->__('Marketplace Upfront Fee Payment Panel') ?></h1>
		</div>
        <form action="https://www.<?php echo $urlfix ?>paypal.com/webscr" id="paypal_standard_checkout" name="paypal_standard_checkout" method="POST">
			<div class="fieldset">
				<h4 class="legend"><?php echo Mage::helper('marketplace')->__('Pay Group Fee') ?></h4>
				<ul class="form-list detail">
					<li>
						<div class="input-box">
							<label><?php echo Mage::Helper('mppartnergroup')->__('Select Seller Type : ')?></label>
							<?php $groups=Mage::getModel('mppartnergroup/mppartnergroup')->getCollection();	?>
							<select class="sellertype required-entry">
								<option disabled selected="selected" value="">
									<?php echo Mage::Helper('mppartnergroup')->__('Select Seller Type');?>
								</option>
								<?php foreach($groups as $group){ ?>
								<option value="<?php echo $group->getGroupCode()?>">
									<?php echo Mage::Helper('mppartnergroup')->__($group->getGroupName());?>
								</option>
								<?php } ?>
							</select>
						</div>
					</li>
					<li>
						<div class="input-box allowed_product">
							<label><?php echo Mage::Helper('mppartnergroup')->__('Number of allowed product : ')?></label>
								<span class="value"></span>
						</div>
					</li>
					<li>
						<div class="input-box wk_amountdata">
							<span class="amount">
								<label><?php echo Mage::Helper('mppartnergroup')->__('Amount : ')?></label>
								<span class="value"></span>
							</span>
						</div>
					</li>
					<input id="business" name="business" value="<?php echo $data['merchant'];?>" type="hidden"/>
					<input id="invoice" name="invoice" value="<?php echo rand(000,99999).'-'.$data['customer_id'];?>" type="hidden"/>
					<input id="currency_code" name="currency_code" value="<?php echo $data['currency_code'];?>" type="hidden"/>
					<input id="paymentaction" name="paymentaction" value="sale" type="hidden"/>
					<input id="return" name="return" value="<?php echo $this->getUrl('mppartnergroup/index')?>" type="hidden"/>
					<input id="cancel_return" name="cancel_return" value="<?php echo $this->getUrl('mppartnergroup/index')?>" type="hidden"/>
					<input id="notify_url" name="notify_url" value="<?php echo $this->getUrl('mppartnergroup/index/ipnnotify')?>" type="hidden"/>
					<input id="bn" name="bn" value="Varien_Cart_WPS_US" type="hidden"/>
					<input id="charset" name="charset" value="utf-8" type="hidden"/>
					<input id="item_name_1" name="item_name_1" value="unassined" type="hidden"/>
					<input id="amount_1" name="amount_1" value="23" type="hidden"/>
					<input id="quantity_1" name="quantity_1" value="1" type="hidden"/>
					<input id="cmd" name="cmd" value="_cart" type="hidden"/>
					<input id="upload" name="upload" value="1" type="hidden"/>
					<input id="tax_cart" name="tax_cart" value="0.00" type="hidden"/>
					<input id="discount_amount_cart" name="discount_amount_cart" value="0.00" type="hidden"/>
					<input id="email" name="email" value="<?php echo $data['email'];?>" type="hidden"/>
					<input id="first_name" name="first_name" value="<?php echo $data['firstname'];?>" type="hidden"/>
					<input id="last_name" name="last_name" value="<?php echo $data['lastname'];?>" type="hidden"/>
				</ul>
			</div>
			<div class="buttons-set">
				<button class="button" title="Pay" type="submit">
					<span><span><?php echo Mage::helper('marketplace')->__('Pay') ?></span></span>
				</button>
			</div>
		</form>
<script type="text/javascript">
if (typeof jQuery == 'undefined'){
    document.write(unescape("%3Cscript src='http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
}
</script> 
<script type="text/javascript">
(function($wk_jq){
        $wk_jq(function(){
        var dataForm = new VarienForm('paypal_standard_checkout', true);
        });
        $wk_jq('.sellertype').change(function(){
			var $temp=$wk_jq(this).val();
			$wk_jq.ajax({
				url:'<?php echo $this->getUrl('mppartnergroup/index/getfeeamount')?>',
				data: {'type':$wk_jq(this).val()},
				type:'POST',
				datatype:'jsonp',
				success: function(data){
					data=JSON.parse(data);
					$wk_jq('.input-box.wk_amountdata,.input-box.allowed_product').css('visibility','visible');
					$wk_jq('.amount .value').text('<?php echo  Mage::app()->getLocale()->currency($data['currency_code'])->getSymbol();?> '+data['amount']);
					$wk_jq('.allowed_product .value').text(data['number_of_product']);
					$wk_jq('#amount_1').val(data['amount']);
					$wk_jq('#item_name_1').val('Seller type '+$temp +' fee');
				}       
			});
        });
})(jQuery);
</script>
<?php  }
        }?>
</div>